# Generated by Django 3.2.10 on 2024-05-15 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('gate_pass_no', models.CharField(max_length=50)),
                ('crew', models.CharField(choices=[('Crew1', 'Crew 1'), ('Crew2', 'Crew 2'), ('Crew3', 'Crew 3'), ('Crew4', 'Crew 4'), ('Crew5', 'Crew 5')], max_length=10)),
                ('designation', models.CharField(choices=[('Designation1', 'Designation 1'), ('Designation2', 'Designation 2'), ('Designation3', 'Designation 3'), ('Designation4', 'Designation 4'), ('Designation5', 'Designation 5')], max_length=15)),
                ('rig_or_rigless', models.CharField(choices=[('Rig', 'Rig'), ('Rigless', 'Rigless')], max_length=10)),
                ('project_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
