# Generated by Django 3.2.10 on 2024-05-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240515_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='backend.crew'),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='backend.designation'),
        ),
    ]
